### ISSUE TITLE
Удалять сообщения с собачкой

### ISSUE THREAD

**Issue by volisok** [f213/discussion-sentinel-bot#19]
Спам в виде сообщений, подписанных названием канала начинающегося с собачки @ проходят фильтр и не удаляются ботом.

**Comment by f213** [comment]
А можете привести пример такого сообщения?

**Comment by volisok** [comment]
Оригинал сразу удалили ручками. Но сейчас поэксперементирую сам… Да, без проблем гость может постить сообщения с ссылками через @

Test message

More text

👉🏿@nameofchannel

**Comment by f213** [comment]
Проверил, сейчас сообщения удаляются, видимо я где-то это пофиксил и не отметил. Если вдруг нет — откройте обратно.
